/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(send_raw24.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(228ea06ab6061ef6ef48785860cb34ea)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <linrad/send_raw24.h>
// pydoc.h is automatically generated in the build directory
#include <send_raw24_pydoc.h>

void bind_send_raw24(py::module& m)
{

    using send_raw24    = ::gr::linrad::send_raw24;


    py::class_<send_raw24, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<send_raw24>>(m, "send_raw24", D(send_raw24))

        .def(py::init(&send_raw24::make),
           py::arg("ip"),
           py::arg("base_port"),
           py::arg("passband_center"),
           py::arg("bufsize"),
           D(send_raw24,make)
        )
        




        
        .def("frequency",&send_raw24::frequency,       
            D(send_raw24,frequency)
        )


        
        .def("set_frequency",&send_raw24::set_frequency,       
            py::arg("freq"),
            D(send_raw24,set_frequency)
        )

        ;




}








